# /booklist/docker-compose.yml
version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: booklist-api
    ports:
      - "8000:8000"
    networks:
      - booklist-network
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: booklist-client
    ports:
      - "5173:5173"
    networks:
      - booklist-network
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

networks:
  booklist-network:
    driver: bridge
