name: CI

on: # est déclenché au push sur la branche "dev"
  push:
    branches:
      - "dev"

jobs:
  test:
    runs-on: ubuntu-latest # spécifie que le job sera exécuté sur la dernière version d'Ubuntu
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # utilise l'action GitHub "checkout" version 3 pour extraire le code

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3 # utilise l'action GitHub "setup-node" version 3 pour installer Node.js
        with:
          node-version: ${{ matrix.node-version }}

      - name: run tests for API
        run: |
          cd api
          npm ci
          npm outdated
          npm run lint
          npm run test

      - name: run tests for Client
        run: |
          cd client
          npm ci
          npm outdated
          npm run lint
          npm run test
