name: CI

on:
  merge:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies and run tests for API
        run: |
          cd api
          npm ci
          npm run lint
          npm run test

      - name: Install dependencies and run tests for Client
        run: |
          cd client
          npm ci
          npm run lint
          npm test
